export enum AggregationType {
    ALL_ITEMS = 'All Items',
    SUM = 'Sum',
    COUNT_UNIQUE = 'Count Unique',
    COUNT_ALL = 'Count All',
    MIN = 'Min',
    MAX = 'Max',
    AVERAGE = 'Average',
    MEDIAN = 'Median',
    VARIANCE = 'Variance',
    STANDARD_DEVIATION = 'Standard Deviation',
    YEARS = 'Years',
    QUARTERS = 'Quarters',
    MONTHS = 'Months',
    WEEKS = 'Weeks',
    DAYS = 'Days',
    TIME = 'Time',
    EVERY_MINUTE = 'Every Minute',
    ROUND_TO_15_MIN = 'Round to 15 Min',
    ROUND_TO_30_MIN = 'Round to 30 Min',
    HOURS = 'Hours',
    OF_YEARS = '# of Years',
    OF_QUARTERS = '# of Quarters',
    OF_MONTHS = '# of Months',
    OF_WEEKS = '# of Weeks',
    OF_DAYS = '# of Days',
}
