export enum WidgetType {
    LINE_CHART = 'chart/line',
    AREA_CHART = 'chart/area',
    PIVOT = 'pivot2',
    BLOX = 'BloX',
    PIE_CHART = 'chart/pie',
    COLUMN_CHART = 'chart/column',
    BAR_CHART = 'chart/bar',
    TREEMAP = 'treemap',
    CALENDAR_HEATMAP = 'heatmap',
    SUNBURST = 'sunburst',
    POLAR_CHART = 'chart/polar',
    FUNNEL_CHART = 'chart/funnel',
    INDICATOR = 'indicator',
    TABLE = 'tablewidget',
    SCATTER_CHART = 'chart/scatter',
    SCATTER_MAP = 'map/scatter',
    AREA_MAP = 'map/area',
    BOX_WHISKER_PLOT = 'chart/boxplot',
}
